// Auto-generated by scripts/deploy.sh — DO NOT EDIT
// Rerun: ./scripts/deploy.sh

/** Matchmaking account ID (deployed on-chain) */
export const MATCHMAKING_ACCOUNT_ID = "";

/** Combat account ID (deployed on-chain) */
export const COMBAT_ACCOUNT_ID = "";

/** @deprecated Use MATCHMAKING_ACCOUNT_ID instead. Alias kept for migration. */
export const ARENA_ACCOUNT_ID = MATCHMAKING_ACCOUNT_ID;

/** Paths to compiled note scripts (served as static assets) */
export const NOTE_SCRIPTS = {
  processStake: "/contracts/process_stake_note.masp",
  processTeam: "/contracts/process_team_note.masp",
  submitMove: "/contracts/submit_move_note.masp",
  initCombat: "/contracts/init_combat_note.masp",
  processResult: "/contracts/process_result_note.masp",
} as const;
