// Auto-generated by scripts/deploy.sh — DO NOT EDIT
// Rerun: ./scripts/deploy.sh

/** Arena account ID (deployed on-chain) */
export const ARENA_ACCOUNT_ID = "";

/** Paths to compiled note scripts (served as static assets) */
export const NOTE_SCRIPTS = {
  processStake: "/contracts/process_stake_note.masp",
  processTeam: "/contracts/process_team_note.masp",
  submitMove: "/contracts/submit_move_note.masp",
} as const;
