#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CONTRACTS_DIR="$REPO_ROOT/contracts"
TARGET_DIR="$REPO_ROOT/target/miden/release"
MASM_OUTPUT="$REPO_ROOT/target/masm-combat"
PUBLIC_DIR="$REPO_ROOT/public/contracts"
CONFIG_FILE="$REPO_ROOT/src/constants/contracts.ts"

# Resolve miden-client binary (midenup installs to Application Support)
MIDEN_CLIENT="${MIDEN_CLIENT:-}"
if [ -z "$MIDEN_CLIENT" ]; then
  if command -v miden-client &> /dev/null; then
    MIDEN_CLIENT="miden-client"
  elif [ -x "$HOME/Library/Application Support/midenup/toolchains/0.20.3/bin/miden-client" ]; then
    MIDEN_CLIENT="$HOME/Library/Application Support/midenup/toolchains/0.20.3/bin/miden-client"
  else
    echo "ERROR: miden-client not found."
    echo "Install via midenup or set MIDEN_CLIENT=/path/to/miden-client"
    exit 1
  fi
fi
echo "Using miden-client: $MIDEN_CLIENT"

echo "=== Step 1: Build all contracts ==="

# Build matchmaking account
(cd "$CONTRACTS_DIR/matchmaking-account" && cargo miden build --release)
MM_WIT="$CONTRACTS_DIR/matchmaking-account/target/generated-wit/miden-matchmaking-account.wit"
if [ ! -f "$MM_WIT" ]; then
  echo "ERROR: Generated WIT not found at $MM_WIT"
  exit 1
fi
mkdir -p "$CONTRACTS_DIR/matchmaking-account/wit"
cp "$MM_WIT" "$CONTRACTS_DIR/matchmaking-account/wit/miden-matchmaking-account.wit"

# Build MASM combat account + its note scripts (init_combat, submit_move)
cargo run -p combat-account-masm --release
# Outputs: target/masm-combat/combat_account.masp
#          target/masm-combat/init_combat_note.masp
#          target/masm-combat/submit_move_note.masp

# Build matchmaking-targeting note scripts (depend on matchmaking WIT)
(cd "$CONTRACTS_DIR/process-stake-note" && cargo miden build --release)
(cd "$CONTRACTS_DIR/process-team-note" && cargo miden build --release)
(cd "$CONTRACTS_DIR/process-result-note" && cargo miden build --release)

echo "=== Step 2: Copy .masp to public/contracts/ ==="
mkdir -p "$PUBLIC_DIR"
# Matchmaking note scripts (from cargo miden build)
cp "$TARGET_DIR/process_stake_note.masp"  "$PUBLIC_DIR/"
cp "$TARGET_DIR/process_team_note.masp"   "$PUBLIC_DIR/"
cp "$TARGET_DIR/process_result_note.masp" "$PUBLIC_DIR/"
# Combat note scripts (from MASM build)
cp "$MASM_OUTPUT/init_combat_note.masp"   "$PUBLIC_DIR/"
cp "$MASM_OUTPUT/submit_move_note.masp"   "$PUBLIC_DIR/"

echo "=== Step 3: Sync client state ==="
"$MIDEN_CLIENT" sync 2>&1 || true

echo "=== Step 4: Deploy matchmaking account ==="
MM_DEPLOY_OUTPUT=$("$MIDEN_CLIENT" new-account \
  --account-type regular-account-updatable-code \
  --storage-mode public \
  -p auth/no-auth \
  -p basic-wallet \
  -p "$TARGET_DIR/matchmaking_account.masp" \
  --deploy 2>&1)

echo "$MM_DEPLOY_OUTPUT"

MATCHMAKING_ID=$(echo "$MM_DEPLOY_OUTPUT" | grep -oE '0x[0-9a-fA-F]+' | head -1)
if [ -z "$MATCHMAKING_ID" ]; then
  echo "ERROR: Failed to extract matchmaking account ID from deployment output"
  exit 1
fi
if [[ ! "$MATCHMAKING_ID" =~ ^0x[0-9a-fA-F]+$ ]]; then
  echo "ERROR: MATCHMAKING_ID contains unexpected characters: $MATCHMAKING_ID"
  exit 1
fi

echo "=== Step 5: Deploy combat account (MASM) ==="
CB_DEPLOY_OUTPUT=$("$MIDEN_CLIENT" new-account \
  --account-type regular-account-updatable-code \
  --storage-mode public \
  -p auth/no-auth \
  -p basic-wallet \
  -p "$MASM_OUTPUT/combat_account.masp" \
  --deploy 2>&1)

echo "$CB_DEPLOY_OUTPUT"

COMBAT_ID=$(echo "$CB_DEPLOY_OUTPUT" | grep -oE '0x[0-9a-fA-F]+' | head -1)
if [ -z "$COMBAT_ID" ]; then
  echo "ERROR: Failed to extract combat account ID from deployment output"
  exit 1
fi
if [[ ! "$COMBAT_ID" =~ ^0x[0-9a-fA-F]+$ ]]; then
  echo "ERROR: COMBAT_ID contains unexpected characters: $COMBAT_ID"
  exit 1
fi

echo "=== Step 6: Write contracts.ts ==="
cat > "$CONFIG_FILE" << EOF
// Auto-generated by scripts/deploy.sh — DO NOT EDIT
// Rerun: ./scripts/deploy.sh

/** Matchmaking account ID (deployed on-chain) */
export const MATCHMAKING_ACCOUNT_ID = "${MATCHMAKING_ID}";

/** Combat account ID (deployed on-chain) */
export const COMBAT_ACCOUNT_ID = "${COMBAT_ID}";

/** @deprecated Use MATCHMAKING_ACCOUNT_ID instead. Alias kept for migration. */
export const ARENA_ACCOUNT_ID = MATCHMAKING_ACCOUNT_ID;

/** Paths to compiled note scripts (served as static assets) */
export const NOTE_SCRIPTS = {
  processStake: "/contracts/process_stake_note.masp",
  processTeam: "/contracts/process_team_note.masp",
  submitMove: "/contracts/submit_move_note.masp",
  initCombat: "/contracts/init_combat_note.masp",
  processResult: "/contracts/process_result_note.masp",
} as const;
EOF

echo ""
echo "=== Deployment complete ==="
echo "Matchmaking Account ID: $MATCHMAKING_ID"
echo "Combat Account ID:      $COMBAT_ID"
echo "Config written to:      $CONFIG_FILE"
echo "Note scripts in:        $PUBLIC_DIR/"
